env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-hooks

settings:
  react:
    version: "detect" # Automatically detects the React version

rules:
  import/extensions: off
  import/no-unresolved: off
  react/prop-types: off
  no-console: off
  react/react-in-jsx-scope: off
  functional/no-conditional-statements: off
  functional/no-expression-statements: off
  functional/immutable-data: off
  functional/functional-parameters: off
  functional/no-try-statement: off
  functional/no-throw-statement: off
  no-underscore-dangle:
    - error
    - allow:
        - "__filename"
        - "__dirname"
  react/function-component-definition:
    - error
    - namedComponents: "arrow-function"
  testing-library/no-debug: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - ".js"
        - ".jsx"
  functional/no-return-void: off
  no-shadow: off
  max-len:
    - error
    - code: 110
  no-alert: off
  no-case-declarations: off
  no-unused-vars:
    - error
    - vars: all
      args: none
  consistent-return: off
  no-nested-ternary: off
  react/no-unescaped-entities: off
  import/prefer-default-export: off
  react-refresh/only-export-components: 0
